### ISSUE TITLE
Mobile Menu Bubble

### ISSUE THREAD

**Issue by taigrr** [heyscrumpy/tiptap#55] opened 2018-10-09 02:18 UTC
# Menu Bubble Android Pie Compatibility 

The Menu Bubble is currently incompatible with Android Pie, as selecting the text brings up a magnifier, and letting go brings up the Android selection context menu.

## Suggestion

Perhaps when viewed in mobile, the Menu Bubble can display /below/ the highlighted text rather than above so that users can still interact with it.

![screenshot_20181008-191258](https://user-images.githubusercontent.com/8261498/46642908-7532d580-cb2e-11e8-9301-e18f1775dc59.png)
![screenshot_20181008-191303](https://user-images.githubusercontent.com/8261498/46642909-76640280-cb2e-11e8-8c31-4c91c0f98ae9.png)

**Comment by philippkuehn** [comment] 2018-10-09 06:50
Duplicate of #37 

A bubble menu is a bad solution for mobile. Just use the regular menu bar. I try to add a solution for v1 to add custom tooltips.

**Closed by philippkuehn** 2018-10-09 06:50 UTC

**Comment by akirarika** [comment] 2019-07-14 08:29
You can:

```javascript
// add this line of code
document.addEventListener("contextmenu", function(e) {
  e.preventDefault();
});
```

It's useful for me. :3
