### ISSUE TITLE
"Tree-Shaking" support for TipTap

### ISSUE THREAD

**Issue by PhouvanhKCSV** [heyscrumpy/tiptap#16] opened 2018-09-06 15:39 UTC
It look like "tiptap-extensions" is load all extensions even i did not use all of them.

```js
import {
    BlockquoteNode,
    BulletListNode,
    HardBreakNode,
    HeadingNode,
    ImageNode,
    ListItemNode,
    OrderedListNode,
    BoldMark,
    ItalicMark,
    HistoryExtension,
  } from 'tiptap-extensions'
```

I use only these extensions but in my vendor file, there is "highlight.js" dependency.

It would be nice if we can import only what we use.

**Comment by philippkuehn** [comment] 2018-09-06 19:20
Oh. This is bad. I don't know how to solve this right now. 😕

**Comment by dannyrb** [comment] 2018-09-06 20:17
I mean, you don't tree shake, you just "support" tree shaking. An example would be... WebPack goes to bundle your code, and it places comments around the modules that weren't used. Usually putting a comment before the unused module like:

`/* unused harmony export <export name> */`

Then a minifier, like uglify, removes the unused code during the minification process. You can read a bit more on it here: https://webpack.js.org/guides/tree-shaking/

See the _requirements_ section:

> - Use ES2015 module syntax (i.e. import and export).
> - Add a "sideEffects" property to your project's package.json file.
> - Use production mode configuration option to enable various optimizations including minification and tree shaking.

**Comment by philippkuehn** [comment] 2018-09-06 21:07
@dannyrb Okay, so I do not have to do anything? 👀 Currently I'm building umd, commonjs and esm versions of all packages with rollup.

**Comment by PhouvanhKCSV** [comment] 2018-09-07 01:03
@dannyrb @philippkuehn That's is what i mean, sorry for my bad explanation.

![webpack bundle analyzer - google chrome_4](https://user-images.githubusercontent.com/10794184/45192649-d2a7de00-b273-11e8-9bbc-61c04d490bd2.jpg)

As you can see, i did not use any "code (highlighting)" extensions like "CodeBlockNode, CodeMark" but a big "highlight.js" is still bundled in the vendor file.

**Comment by dannyrb** [comment] 2018-09-07 01:06
@philippkuehn, I think the only thing you would need to add (for consumers of your library that are using WebPack) is the `sideEffects` information in `package.json`:

```
{
  "name": "tiptap-packages",
  "sideEffects": false,
   ...
}
```

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

@PhouvanhKCSV, I think you need to import:

`import tiptap from 'tiptap/dist/tiptap.esm.js'` instead of
`import tiptap from 'tiptap'`

Someone with more knowledge in this area might be able to help further. I only have a passing knowledge of most of this 😅

**Comment by philippkuehn** [comment] 2018-09-07 07:53
@PhouvanhKCSV I've released v0.10.1 and added this sideEffects option to the extenstions package.

Maybe you could test it again?

**Comment by dannyrb** [comment] 2018-09-07 13:28
I think @philippkuehn has done everything he needs to. This is likely a configuration/setup issue. Here's a Medium article that may help?

https://medium.com/@joanxie/utilize-webpacks-tree-shaking-in-your-vue-application-a0dc63c0dfac

This could be the culprit?

> 3. Ensure that your source code files are still in their ES module form when loaded by Babel
Both es2015 and env presets will by default transpile the ES module syntax to the CommonJS module format. Ensure that both presets have "modules": false set.

I hate tagging him, because I know he has infinitely better things to do, but I'm sure @TheLarkinn or someone else from the WebPack team would be able to offer insight.

**Comment by philippkuehn** [comment] 2018-09-09 20:26
Another solution I think about is to move all extension to its own package.

```js
import BlockquoteNode from 'tiptap-bockquote-extension'
import BulletListNode from 'tiptap-bulletlist-extension'
import HardBreakNode from 'tiptap-hardbreak-extension'
import HeadingNode from 'tiptap-heading-extension'
// ...
```
That would solve this issue too but I'm not sure if this is »too much«!? 🤔

**Comment by erickwilder** [comment] 2018-10-10 13:19
I have the same issue here. I've created a test repo with a reproducible example:
https://github.com/erickwilder/tiptap-treeshaking

I'm willing to help you to investigate if this is an issue with `tiptap` or something that could be fixed by tweaking the project configuration. Bear in mind that the test repo was created with some of the defaults provided by `@vue/cli` and I assume that their work to optimize the production bundle took a lot in consideration regarding correct bundling.

**Comment by philippkuehn** [comment] 2018-10-10 18:08
@erickwilder Thank you for this repo! `@vue/cli` should definitely support tree shaking so maybe there is still something to do on my side.

**Comment by erickwilder** [comment] 2018-10-10 20:50
@philippkuehn I think that the issue lies down in the fact that `tiptap-extension` is using the full `lowlight` library even tough the authors recommend to use just what you really need to:

> I do not suggest using the pre-built files or requiring lowlight in the browser as that would include a 684kb (196kb GZipped) file.
> 
> Instead, require lowlight/lib/core, and include only the used highlighters. For example:

```
var low = require('lowlight/lib/core');
var js = require('highlight.js/lib/languages/javascript');

low.registerLanguage('javascript', js);

low.highlight('js', '"use strict";');
```

I didn't have the time yet but I'll try to patch the `CodeBlockHighlight.js` file to come up with a way to lazy-load required files.

**Comment by philippkuehn** [comment] 2018-10-10 21:53
Yeah. First I thought that it would be nice to pass some names of languages to lazy load the required modules within the extension. But I think lazy load won‘t work here because of the build setup with rollup. We would like to get this magic dynamic imports from webpack here to move these  to its own chunks.

Instead I think of loading the required languages on user side and pass these to the extension.

**Comment by erickwilder** [comment] 2018-10-11 07:59
I agree. Before I start diving into code, let's just agree with the design of the interface of it. One possible idea could be something like passing a list _previously registered_ languages when calling `CodeBlockHIghlight`'s constructor:

```
extensions: [
  new CodeBlockHighLight({languages: [javascript, markdown, python]}
]
```

**Comment by philippkuehn** [comment] 2018-10-11 08:28
Yes, that syntax would be perfect. But unfortunately this will not be possible with lazy loading. But maybe I'm wrong.

So I thought of moving the import stuff to the user side? 🤷‍♂️

```js
extensions: [
  new CodeBlockHighLight({
    languages: {
      javascript: require('highlight.js/lib/languages/javascript'),
      markdown: require('highlight.js/lib/languages/markdown'),
      python: require('highlight.js/lib/languages/python'),
    },
  }),
]
```

**Comment by erickwilder** [comment] 2018-10-11 11:34
Yes. This is what I meant. The language variables would be import/required
modules from lowlight. I'll submit a patch

**Closed** 2018-10-13 16:18 UTC
Labels: hacktoberfest, help wanted
